using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Map_List {

	public static Map_Tile[,] test_map_1 = new Map_Tile[20,20]{
		
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Deciduous_Forest,Map_Tile.Deciduous_Forest,Map_Tile.Deciduous_Forest,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Deciduous_Forest,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Deciduous_Forest,Map_Tile.Deciduous_Forest,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Deciduous_Forest,Map_Tile.Deciduous_Forest,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Deciduous_Forest,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Deciduous_Forest,Map_Tile.Deciduous_Forest,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Deciduous_Forest,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Deciduous_Forest,Map_Tile.Deciduous_Forest,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Deciduous_Forest,Map_Tile.Deciduous_Forest,Map_Tile.Deciduous_Forest,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Deciduous_Forest,Map_Tile.Deciduous_Forest,Map_Tile.Deciduous_Forest,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Deciduous_Forest,Map_Tile.Deciduous_Forest,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Deciduous_Forest,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland}
	};


	public static Map_Tile[,] test_map_2 = new Map_Tile[20,20]{
		
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Deciduous_Forest,Map_Tile.Deciduous_Forest,Map_Tile.Deciduous_Forest,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Deciduous_Forest,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Deciduous_Forest,Map_Tile.Deciduous_Forest,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Deciduous_Forest,Map_Tile.Deciduous_Forest,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Deciduous_Forest,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Deciduous_Forest,Map_Tile.Deciduous_Forest,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Deciduous_Forest,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Deciduous_Forest,Map_Tile.Deciduous_Forest,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Deciduous_Forest,Map_Tile.Deciduous_Forest,Map_Tile.Deciduous_Forest,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Deciduous_Forest,Map_Tile.Deciduous_Forest,Map_Tile.Deciduous_Forest,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Deciduous_Forest,Map_Tile.Deciduous_Forest,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Deciduous_Forest,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland}
	};
	
	public static Map_Tile[,] test_map_watercliff = new Map_Tile[10,10]{
		
		{Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Grassland,Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Grassland},
		{Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea},
		{Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea},
		{Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Sea},
		{Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Sea},
		{Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Sea},
		{Map_Tile.Sea,Map_Tile.Grassland,Map_Tile.Grassland,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea},
		{Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea},
		{Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea,Map_Tile.Sea},
	};
}